### ISSUE TITLE
Expand-Path Cannot Handle Dot Directories. Robocopy XF and XD Filter Broken Switch Behavior.

### ISSUE THREAD

**Issue by ceejbro** [renevaessen/GenXdev.FileSystem#1]
Using PowerShell 5.1.19041.1320

Expand-Path . or Expand-Path ./Directory/File would fail with 

> Exception calling "GetFullPath" with "1" argument(s): "The given path's format is not supported." At C:\Program Files\WindowsPowerShell\Modules\GenXdev.FileSystem\1.32.2021\GenXdev.FileSystem.psm1:146 char:9

Fixed by adding a check for dot directory and using Convert-Path.

Start-Robocopy -FileExcludeFilter "*.file" would fail because it enumerates the switches out into 

> robocopy .... /XF /'*.file'

Which fails because it's not a switch. Added logic to differentiate the FileFilters from the other switches, but this is just a workaround since I don't fully know the architecture of the script and didn't want to break other dependencies.

**Comment by skaravos** [comment]
Maybe this should be split into two separate issues?

Issue 1: Expand-Path dot directories

Issue 2: Broken filter switches

+1 on the file filter issue, this is definitely broken and is a very common switch

*NOTE: I am not able to reproduce the `Expand-Path  .` problem on my local machine.*

**Comment by renevaessen** [comment]
Thanks for all the help!
